name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: curl -fsSL https://bun.sh/install | bash
      - run: echo "${HOME}/.bun/bin" >> $GITHUB_PATH
      - run: make setup
      - run: make build
      - run: make lint
      - run: make format
      - run: make clean
