name: GitHub Pages

on:
  workflow_run:
    workflows: [CI]
    branches: [main]
    types:
      - completed

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: make setup
      - run: make build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist/unofficial.cubing.net/
          retention-days: 1

  deploy-pages:
    runs-on: ubuntu-latest

    needs: build-pages

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    # https://github.com/actions/deploy-pages#usage
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
